// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcaD0ITAlKVRyyZO21IhY2s9Wfed_vEAg',
    appId: '1:18675576484:web:c769c9c646924cc494c031',
    messagingSenderId: '18675576484',
    projectId: 'cmsc23b7l-5717a',
    authDomain: 'cmsc23b7l-5717a.firebaseapp.com',
    storageBucket: 'cmsc23b7l-5717a.appspot.com',
    measurementId: 'G-C3HFM60WSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvwnAvKKj1nsyQn0_kSHQY49G8Fm_OzcA',
    appId: '1:18675576484:android:5fe8a10772257c0394c031',
    messagingSenderId: '18675576484',
    projectId: 'cmsc23b7l-5717a',
    storageBucket: 'cmsc23b7l-5717a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3OY4oYDq3xbnSjm8fv1mLrKh7Wflecyg',
    appId: '1:18675576484:ios:5938ff5564351e9694c031',
    messagingSenderId: '18675576484',
    projectId: 'cmsc23b7l-5717a',
    storageBucket: 'cmsc23b7l-5717a.appspot.com',
    iosClientId: '18675576484-565t4bs4cl22lkfb30kd9gj7ihu8vehc.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3OY4oYDq3xbnSjm8fv1mLrKh7Wflecyg',
    appId: '1:18675576484:ios:5938ff5564351e9694c031',
    messagingSenderId: '18675576484',
    projectId: 'cmsc23b7l-5717a',
    storageBucket: 'cmsc23b7l-5717a.appspot.com',
    iosClientId: '18675576484-565t4bs4cl22lkfb30kd9gj7ihu8vehc.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
